### PR TITLE
updates docs and code for rate limiting

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
cf #57

**Comment by aedobbyn** [comment]
Looks good to me! I think setting the default to 120 if plan is custom is a good bet, since it's likely to be higher. If we have it too high, though (let's say their actual rate is 60), will `ratelimitr` back off appropriately?

**Comment by maelle** [comment]
`ratelimitr` no but the part about 429 errors yes

**Comment by aedobbyn** [comment]
Okay, that should be fine, I think!

**Comment by maelle** [comment]
:pray:

**Pull request merged**
