### PR TITLE
T94: add an input with >20 empty string inputs to the vignette

### PR DESCRIPTION
**Pull request by aedobbyn**

### CODE REVIEW

**Comment by maelle** [comment]
Nice! Could you also update the website docs via `pkgdown::build_articles` (IIRC)?

**Comment by aedobbyn** [comment]
Done! For some reason an inline R chunk wouldn't work (referencing `speedup` in line 287) so I took that out for now. Thought it might be some caching issue but I don't see where the cache for `pkgdown` is stored

**Comment by maelle** [comment]
Oh interesting, but not too bad I guess! I don't know where the cache is either, I'd suggest either deleting everything in docs or ignoring the problem for now. 😁

**Comment by aedobbyn** [comment]
Haha okay! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
