### PR TITLE
close #53 by making README minimal

### LINKED ISSUE #53: Pare down the README to just installation and minimal examples and link to pkgdown articles

### PR DESCRIPTION
**Pull request by maelle**
@aedobbyn I also decided to start listing use cases. I do not intend to only have _mine_ :joy:

### CODE REVIEW

**Comment by aedobbyn** [comment]
WOW had no idea you'd used the package for so many cool projects! I can't wait to read all of these.

The first one we can put under using the new functions can be the UrbanDictionary API idea?

**Comment by maelle** [comment]
Hey true. You can add it as a vignette and/or on your blog. 

I can't remember where I had written that idea 🤔 😂

**Comment by aedobbyn** [comment]
It was here! https://github.com/ropensci/onboarding/issues/45 on Jul 30, 2016

**Comment by maelle** [comment]
sounds good!

**Pull request merged**
